// <auto-generated />
using GestionScolaire.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GestionScolaire.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260418031044_AddCours")]
    partial class AddCours
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GestionScolaire.API.Models.Cours", b =>
                {
                    b.Property<int>("IdCours")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCours"));

                    b.Property<bool>("Actif")
                        .HasColumnType("bit");

                    b.Property<int>("Credit")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Duree")
                        .HasColumnType("int");

                    b.Property<int>("IdNiveau")
                        .HasColumnType("int");

                    b.Property<int>("IdProgramme")
                        .HasColumnType("int");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ProgrammeIdProgramme")
                        .HasColumnType("int");

                    b.HasKey("IdCours");

                    b.HasIndex("ProgrammeIdProgramme");

                    b.ToTable("Cours");
                });

            modelBuilder.Entity("GestionScolaire.API.Models.Programme", b =>
                {
                    b.Property<int>("IdProgramme")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdProgramme"));

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdProgramme");

                    b.ToTable("Programmes");
                });

            modelBuilder.Entity("GestionScolaire.API.Models.Cours", b =>
                {
                    b.HasOne("GestionScolaire.API.Models.Programme", "Programme")
                        .WithMany("Cours")
                        .HasForeignKey("ProgrammeIdProgramme");

                    b.Navigation("Programme");
                });

            modelBuilder.Entity("GestionScolaire.API.Models.Programme", b =>
                {
                    b.Navigation("Cours");
                });
#pragma warning restore 612, 618
        }
    }
}
